vaadin/flow-spring-examples

.gitignore, README.md, pom.xml, src/main/java/org/vaadin/spring/tutorial/TutorialApplication.java, src/main/resources/META-INF/resources/frontend/bower.json, src/main/resources/META-INF/resources/frontend/index.html, src/main/resources/META-INF/resources/frontend/package-lock.json, src/main/resources/META-INF/resources/frontend/package.json, src/main/resources/META-INF/resources/frontend/polymer.json
Fix for #2573
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/1)
=> Make initial Spring tutorial project structure

src/main/java/org/vaadin/spring/tutorial/TutorialApplication.java
The first step to fix #2574
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/2)
=> I - Getting Started with Vaadin Spring for Flow and Spring Boot

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/7)
=> Enable travis for the project

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/8)
=> Fix spring boot starter version

src/main/java/org/vaadin/spring/tutorial/ViewComponent.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/4)
=> III - Navigation with Vaadin Spring

src/main/java/org/vaadin/spring/tutorial/AddMetaServiceInitListener.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/6)
=> V - Register VaadinServiceInitListener via the Spring DI mechanism

src/main/java/org/vaadin/spring/tutorial/ExampleTemplate.java, src/main/java/org/vaadin/spring/tutorial/RootComponent.java, src/main/resources/META-INF/resources/frontend/ExampleTemplate.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/5)
=> IV - Flow template with Spring Boot

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/9)
=> Update Flow version.

pom.xml, src/main/java/org/vaadin/spring/tutorial/AddMetaServiceInitListener.java, src/main/java/org/vaadin/spring/tutorial/ExampleTemplate.java, src/main/java/org/vaadin/spring/tutorial/Greeter.java, src/main/java/org/vaadin/spring/tutorial/RootComponent.java, src/main/java/org/vaadin/spring/tutorial/ViewComponent.java
remove flow.project.version from POM;
update imports
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/12)
=> Update to Platform alpha12

README.md
Fix for #3179
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/16)
=> Add a list of features covered by the tutorial project

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/17)
=> Added logger dependency

README.md, src/main/java/org/vaadin/spring/tutorial/RootComponent.java, src/main/java/org/vaadin/spring/tutorial/SimpleI18NProvider.java
Fix for #3180
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/18)
=> Make the router link localized and provide a way to change locale

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/19)
=> Update platform to alpha18

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/23)
=> Update platform to beta1

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/24)
=> Update platform version to beta3

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/27)
=> Update platform version to beta7

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/28)
=> Update vaadin.version to beta8

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/29)
=> Update Spring dependency artifact

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/30)
=> Update Spring-boot.version to 2.0.0.RELEASE

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/32)
=> Update the link the in README about tutorial

pom.xml, src/main/java/org/vaadin/spring/tutorial/RootComponent.java, src/main/java/org/vaadin/spring/tutorial/SimpleI18NProvider.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/33)
=> Update platform to beta9

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/38)
=> Update platform and spring-boot version

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/39)
=> Update platform to RC 3

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/45)
=> Update jackson.version to avoid vulnerabilities

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/49)
=> Update jackson-databind version to fix security alert.
